/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrgRouteImport } from './routes/$org'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrgIndexRouteImport } from './routes/$org/index'
import { Route as OrgToolsRouteImport } from './routes/$org/tools'
import { Route as OrgSettingsRouteImport } from './routes/$org/settings'
import { Route as OrgSecretsRouteImport } from './routes/$org/secrets'
import { Route as OrgBillingRouteImport } from './routes/$org/billing'
import { Route as OrgSourcesNamespaceRouteImport } from './routes/$org/sources.$namespace'
import { Route as OrgBillingPlansRouteImport } from './routes/$org/billing_.plans'
import { Route as OrgSourcesAddPluginKeyRouteImport } from './routes/$org/sources.add.$pluginKey'

const OrgRoute = OrgRouteImport.update({
  id: '/$org',
  path: '/$org',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgIndexRoute = OrgIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrgRoute,
} as any)
const OrgToolsRoute = OrgToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSettingsRoute = OrgSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSecretsRoute = OrgSecretsRouteImport.update({
  id: '/secrets',
  path: '/secrets',
  getParentRoute: () => OrgRoute,
} as any)
const OrgBillingRoute = OrgBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSourcesNamespaceRoute = OrgSourcesNamespaceRouteImport.update({
  id: '/sources/$namespace',
  path: '/sources/$namespace',
  getParentRoute: () => OrgRoute,
} as any)
const OrgBillingPlansRoute = OrgBillingPlansRouteImport.update({
  id: '/billing_/plans',
  path: '/billing/plans',
  getParentRoute: () => OrgRoute,
} as any)
const OrgSourcesAddPluginKeyRoute = OrgSourcesAddPluginKeyRouteImport.update({
  id: '/sources/add/$pluginKey',
  path: '/sources/add/$pluginKey',
  getParentRoute: () => OrgRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$org': typeof OrgRouteWithChildren
  '/$org/billing': typeof OrgBillingRoute
  '/$org/secrets': typeof OrgSecretsRoute
  '/$org/settings': typeof OrgSettingsRoute
  '/$org/tools': typeof OrgToolsRoute
  '/$org/': typeof OrgIndexRoute
  '/$org/billing/plans': typeof OrgBillingPlansRoute
  '/$org/sources/$namespace': typeof OrgSourcesNamespaceRoute
  '/$org/sources/add/$pluginKey': typeof OrgSourcesAddPluginKeyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$org/billing': typeof OrgBillingRoute
  '/$org/secrets': typeof OrgSecretsRoute
  '/$org/settings': typeof OrgSettingsRoute
  '/$org/tools': typeof OrgToolsRoute
  '/$org': typeof OrgIndexRoute
  '/$org/billing/plans': typeof OrgBillingPlansRoute
  '/$org/sources/$namespace': typeof OrgSourcesNamespaceRoute
  '/$org/sources/add/$pluginKey': typeof OrgSourcesAddPluginKeyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$org': typeof OrgRouteWithChildren
  '/$org/billing': typeof OrgBillingRoute
  '/$org/secrets': typeof OrgSecretsRoute
  '/$org/settings': typeof OrgSettingsRoute
  '/$org/tools': typeof OrgToolsRoute
  '/$org/': typeof OrgIndexRoute
  '/$org/billing_/plans': typeof OrgBillingPlansRoute
  '/$org/sources/$namespace': typeof OrgSourcesNamespaceRoute
  '/$org/sources/add/$pluginKey': typeof OrgSourcesAddPluginKeyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$org'
    | '/$org/billing'
    | '/$org/secrets'
    | '/$org/settings'
    | '/$org/tools'
    | '/$org/'
    | '/$org/billing/plans'
    | '/$org/sources/$namespace'
    | '/$org/sources/add/$pluginKey'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$org/billing'
    | '/$org/secrets'
    | '/$org/settings'
    | '/$org/tools'
    | '/$org'
    | '/$org/billing/plans'
    | '/$org/sources/$namespace'
    | '/$org/sources/add/$pluginKey'
  id:
    | '__root__'
    | '/'
    | '/$org'
    | '/$org/billing'
    | '/$org/secrets'
    | '/$org/settings'
    | '/$org/tools'
    | '/$org/'
    | '/$org/billing_/plans'
    | '/$org/sources/$namespace'
    | '/$org/sources/add/$pluginKey'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgRoute: typeof OrgRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/$org': {
      id: '/$org'
      path: '/$org'
      fullPath: '/$org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$org/': {
      id: '/$org/'
      path: '/'
      fullPath: '/$org/'
      preLoaderRoute: typeof OrgIndexRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/tools': {
      id: '/$org/tools'
      path: '/tools'
      fullPath: '/$org/tools'
      preLoaderRoute: typeof OrgToolsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/settings': {
      id: '/$org/settings'
      path: '/settings'
      fullPath: '/$org/settings'
      preLoaderRoute: typeof OrgSettingsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/secrets': {
      id: '/$org/secrets'
      path: '/secrets'
      fullPath: '/$org/secrets'
      preLoaderRoute: typeof OrgSecretsRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/billing': {
      id: '/$org/billing'
      path: '/billing'
      fullPath: '/$org/billing'
      preLoaderRoute: typeof OrgBillingRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/sources/$namespace': {
      id: '/$org/sources/$namespace'
      path: '/sources/$namespace'
      fullPath: '/$org/sources/$namespace'
      preLoaderRoute: typeof OrgSourcesNamespaceRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/billing_/plans': {
      id: '/$org/billing_/plans'
      path: '/billing/plans'
      fullPath: '/$org/billing/plans'
      preLoaderRoute: typeof OrgBillingPlansRouteImport
      parentRoute: typeof OrgRoute
    }
    '/$org/sources/add/$pluginKey': {
      id: '/$org/sources/add/$pluginKey'
      path: '/sources/add/$pluginKey'
      fullPath: '/$org/sources/add/$pluginKey'
      preLoaderRoute: typeof OrgSourcesAddPluginKeyRouteImport
      parentRoute: typeof OrgRoute
    }
  }
}

interface OrgRouteChildren {
  OrgBillingRoute: typeof OrgBillingRoute
  OrgSecretsRoute: typeof OrgSecretsRoute
  OrgSettingsRoute: typeof OrgSettingsRoute
  OrgToolsRoute: typeof OrgToolsRoute
  OrgIndexRoute: typeof OrgIndexRoute
  OrgBillingPlansRoute: typeof OrgBillingPlansRoute
  OrgSourcesNamespaceRoute: typeof OrgSourcesNamespaceRoute
  OrgSourcesAddPluginKeyRoute: typeof OrgSourcesAddPluginKeyRoute
}

const OrgRouteChildren: OrgRouteChildren = {
  OrgBillingRoute: OrgBillingRoute,
  OrgSecretsRoute: OrgSecretsRoute,
  OrgSettingsRoute: OrgSettingsRoute,
  OrgToolsRoute: OrgToolsRoute,
  OrgIndexRoute: OrgIndexRoute,
  OrgBillingPlansRoute: OrgBillingPlansRoute,
  OrgSourcesNamespaceRoute: OrgSourcesNamespaceRoute,
  OrgSourcesAddPluginKeyRoute: OrgSourcesAddPluginKeyRoute,
}

const OrgRouteWithChildren = OrgRoute._addFileChildren(OrgRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgRoute: OrgRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
